services:
  banana-flow-admin:
    container_name: banana-flow-admin
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '18002:80'
    # 映射 host.docker.internal 到宿主机 IP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /opt/banana-flow-admin/dist:/usr/share/nginx/html
      - /opt/banana-flow-admin/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - common2-network