"""add_image_management

Revision ID: 5280ddc250d5
Revises: baeac99d3760
Create Date: 2026-03-25 16:27:08.951796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5280ddc250d5'
down_revision: Union[str, Sequence[str], None] = 'baeac99d3760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img_directory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='目录ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级目录ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='目录名称'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['img_directory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_img_directory_is_deleted'), 'img_directory', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_img_directory_user_id'), 'img_directory', ['user_id'], unique=False)
    op.create_table('img_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='虚拟文件ID'),
    sa.Column('dir_id', sa.Integer(), nullable=True, comment='所属目录ID'),
    sa.Column('file_id', sa.Integer(), nullable=False, comment='关联的物理文件ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='显示的文件名'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['dir_id'], ['img_directory.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['sys_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_img_file_is_deleted'), 'img_file', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_img_file_user_id'), 'img_file', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_img_file_user_id'), table_name='img_file')
    op.drop_index(op.f('ix_img_file_is_deleted'), table_name='img_file')
    op.drop_table('img_file')
    op.drop_index(op.f('ix_img_directory_user_id'), table_name='img_directory')
    op.drop_index(op.f('ix_img_directory_is_deleted'), table_name='img_directory')
    op.drop_table('img_directory')
    # ### end Alembic commands ###
