"""init

Revision ID: baeac99d3760
Revises: 
Create Date: 2026-03-03 12:42:34.428781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baeac99d3760'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('device_id', sa.String(length=50), nullable=False, comment='设备编号'),
    sa.Column('device_name', sa.String(length=100), nullable=False, comment='设备名称'),
    sa.Column('device_type', sa.String(length=50), nullable=True, comment='设备类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='设备状态:运行/停机/报警/维护'),
    sa.Column('alarm_level', sa.String(length=20), nullable=True, comment='报警级别:无/低/中/高'),
    sa.Column('alarm_info', sa.Text(), nullable=True, comment='报警详情'),
    sa.Column('temperature', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='温度(℃)'),
    sa.Column('humidity', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='湿度(%)'),
    sa.Column('pressure', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='压力(MPa)'),
    sa.Column('voltage', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='电压(V)'),
    sa.Column('current', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='电流(A)'),
    sa.Column('vibration', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='振动值(mm/s)'),
    sa.Column('production_count', sa.Integer(), nullable=True, comment='生产计数'),
    sa.Column('energy_consumption', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='能耗(kWh)'),
    sa.Column('record_time', sa.DateTime(), nullable=False, comment='记录时间'),
    sa.Column('operator', sa.String(length=50), nullable=True, comment='操作员'),
    sa.Column('workshop', sa.String(length=50), nullable=True, comment='车间'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_info_device_id'), 'device_info', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_info_id'), 'device_info', ['id'], unique=False)
    op.create_index(op.f('ix_device_info_record_time'), 'device_info', ['record_time'], unique=False)
    op.create_index(op.f('ix_device_info_status'), 'device_info', ['status'], unique=False)
    op.create_index(op.f('ix_device_info_workshop'), 'device_info', ['workshop'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='操作用户名'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='业务模块'),
    sa.Column('action', sa.String(length=100), nullable=True, comment='操作描述'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='请求方法'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='请求路径'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理'),
    sa.Column('os', sa.String(length=50), nullable=True, comment='操作系统'),
    sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='地理位置'),
    sa.Column('request_params', sa.JSON(), nullable=True, comment='请求参数'),
    sa.Column('response_data', sa.JSON(), nullable=True, comment='响应数据'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='状态码'),
    sa.Column('execution_time', sa.Integer(), nullable=True, comment='执行耗时(ms)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.create_table('pages_generate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_key', sa.String(length=50), nullable=True, comment='页面唯一标识'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='页面标题'),
    sa.Column('config_json', sa.JSON(), nullable=True, comment='解析后的DSL JSON数据'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_generate_id'), 'pages_generate', ['id'], unique=False)
    op.create_index(op.f('ix_pages_generate_page_key'), 'pages_generate', ['page_key'], unique=True)
    op.create_table('sys_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='文件ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('storage_name', sa.String(length=255), nullable=False, comment='存储文件名(UUID)'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='相对路径'),
    sa.Column('file_url', sa.String(length=255), nullable=False, comment='访问URL'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件扩展名'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='上传者ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_name')
    )
    op.create_index(op.f('ix_sys_file_is_deleted'), 'sys_file', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_file_user_id'), 'sys_file', ['user_id'], unique=False)
    op.create_table('sys_notice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('notice_type', sa.Integer(), nullable=True, comment='类型: 1-通知 2-公告 3-私信'),
    sa.Column('publisher_id', sa.Integer(), nullable=True, comment='发布者ID'),
    sa.Column('publisher_name', sa.String(length=50), nullable=True, comment='发布者姓名'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_notice_id'), 'sys_notice', ['id'], unique=False)
    op.create_index(op.f('ix_sys_notice_is_deleted'), 'sys_notice', ['is_deleted'], unique=False)
    op.create_table('sys_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='权限ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='菜单标题/权限名称'),
    sa.Column('type', sa.Integer(), nullable=False, comment='类型: 1-菜单 2-按钮/接口'),
    sa.Column('code', sa.String(length=100), nullable=True, comment='权限标识(ex: system:user:add)'),
    sa.Column('is_custom_name', sa.Boolean(), nullable=True, comment='是否自定义路由名称'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='路由名称'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='链接地址'),
    sa.Column('component_path', sa.String(length=200), nullable=True, comment='组件路径'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标'),
    sa.Column('redirect', sa.String(length=200), nullable=True, comment='重定向路径'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序权重'),
    sa.Column('keep_alive', sa.Boolean(), nullable=True, comment='是否缓存'),
    sa.Column('hide_in_menu', sa.Boolean(), nullable=True, comment='是否在菜单隐藏'),
    sa.Column('active_menu', sa.String(length=200), nullable=True, comment='指定高亮菜单'),
    sa.Column('is_login', sa.Boolean(), nullable=True, comment='是否需要登录'),
    sa.Column('link', sa.String(length=500), nullable=True, comment='外部链接'),
    sa.Column('permanent', sa.Boolean(), nullable=True, comment='是否永久缓存'),
    sa.Column('single_menu', sa.Boolean(), nullable=True, comment='是否单菜单'),
    sa.Column('auth', sa.JSON(), nullable=True, comment="权限标识数组 ['system:user:add']"),
    sa.Column('auths', sa.JSON(), nullable=True, comment='权限池对象数组'),
    sa.Column('hide_breadcrumb', sa.Boolean(), nullable=True, comment='是否隐藏面包屑'),
    sa.Column('query', sa.JSON(), nullable=True, comment='查询参数'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_permissions_id'), 'sys_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_permissions_is_deleted'), 'sys_permissions', ['is_deleted'], unique=False)
    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('role_code', sa.String(length=50), nullable=False, comment='角色编码(ex: admin)'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='角色状态'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否系统内置角色'),
    sa.Column('role_level', sa.Integer(), nullable=False, comment='角色等级(0-超级管理员, 1-系统管理员, 10-普通用户, 100-访客)'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code')
    )
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=False)
    op.create_index(op.f('ix_sys_role_is_deleted'), 'sys_role', ['is_deleted'], unique=False)
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='账号'),
    sa.Column('password_hash', sa.String(length=100), nullable=False, comment='加密密码'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('mobile_phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='性别(0-未知, 1-男, 2-女)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='账户状态'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否系统内置用户'),
    sa.Column('last_login_time', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=False)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_is_deleted'), 'sys_user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_user_mobile_phone'), 'sys_user', ['mobile_phone'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sys_user_notice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='阅读时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['sys_notice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_notice_id'), 'sys_user_notice', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_notice_is_deleted'), 'sys_user_notice', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_user_notice_is_read'), 'sys_user_notice', ['is_read'], unique=False)
    op.create_index(op.f('ix_sys_user_notice_notice_id'), 'sys_user_notice', ['notice_id'], unique=False)
    op.create_index(op.f('ix_sys_user_notice_user_id'), 'sys_user_notice', ['user_id'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_sys_user_notice_user_id'), table_name='sys_user_notice')
    op.drop_index(op.f('ix_sys_user_notice_notice_id'), table_name='sys_user_notice')
    op.drop_index(op.f('ix_sys_user_notice_is_read'), table_name='sys_user_notice')
    op.drop_index(op.f('ix_sys_user_notice_is_deleted'), table_name='sys_user_notice')
    op.drop_index(op.f('ix_sys_user_notice_id'), table_name='sys_user_notice')
    op.drop_table('sys_user_notice')
    op.drop_table('sys_role_permission')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_mobile_phone'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_is_deleted'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_is_deleted'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_permissions_is_deleted'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_id'), table_name='sys_permissions')
    op.drop_table('sys_permissions')
    op.drop_index(op.f('ix_sys_notice_is_deleted'), table_name='sys_notice')
    op.drop_index(op.f('ix_sys_notice_id'), table_name='sys_notice')
    op.drop_table('sys_notice')
    op.drop_index(op.f('ix_sys_file_user_id'), table_name='sys_file')
    op.drop_index(op.f('ix_sys_file_is_deleted'), table_name='sys_file')
    op.drop_table('sys_file')
    op.drop_index(op.f('ix_pages_generate_page_key'), table_name='pages_generate')
    op.drop_index(op.f('ix_pages_generate_id'), table_name='pages_generate')
    op.drop_table('pages_generate')
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_device_info_workshop'), table_name='device_info')
    op.drop_index(op.f('ix_device_info_status'), table_name='device_info')
    op.drop_index(op.f('ix_device_info_record_time'), table_name='device_info')
    op.drop_index(op.f('ix_device_info_id'), table_name='device_info')
    op.drop_index(op.f('ix_device_info_device_id'), table_name='device_info')
    op.drop_table('device_info')
    # ### end Alembic commands ###
