# 角色数据
INIT_ROLES = [
    {
        "roleName": "超级管理员",
        "roleCode": "super_admin",
        "status": True,
        "sort": 1,
        "isSystem": True,
        "roleLevel": 0,
    },
    {
        "roleName": "管理员",
        "roleCode": "admin",
        "status": True,
        "sort": 2,
        "isSystem": True,
        "roleLevel": 1,
    },
    {
        "roleName": "普通用户",
        "roleCode": "user",
        "status": True,
        "sort": 3,
        "isSystem": True,
        "roleLevel": 10,
        "menu_ids": [1, 2, 3, 4, 5, 6, 66],
    },
    {
        "roleName": "设计角色",
        "roleCode": "designer",
        "status": True,
        "sort": 4,
        "isSystem": True,
        "roleLevel": 10,
        "menu_ids": [1, 2, 3, 4, 5, 6, 66, 67],
    },
    {
        "roleName": "产品角色",
        "roleCode": "product",
        "status": True,
        "sort": 5,
        "isSystem": True,
        "roleLevel": 10,
        "menu_ids": [1, 2, 3, 4, 5, 6, 66, 68],
    },
]

# 用户数据
INIT_USERS = [
    {
        "nickname": "超级管理员",
        "email": "superAdmin@example.com",
        "mobilePhone": "",
        "avatar": None,
        "gender": 0,
        "username": "superAdmin",
        "isActive": True,
        "roles": [{"roleCode": "super_admin"}],
    },
    {
        "nickname": "管理员",
        "email": "admin@example.com",
        "mobilePhone": None,
        "avatar": None,
        "gender": None,
        "username": "admin",
        "isActive": True,
        "roles": [{"roleCode": "admin"}],
    },
    {
        "nickname": "普通用户",
        "email": "user@example.com",
        "mobilePhone": None,
        "avatar": None,
        "gender": None,
        "username": "user",
        "isActive": True,
        "roles": [{"roleCode": "user"}],
    },
    {
        "nickname": "设计-张三",
        "email": "zhangsan@example.com",
        "mobilePhone": None,
        "avatar": None,
        "gender": None,
        "username": "zhangsan",
        "isActive": True,
        "roles": [{"roleCode": "user"}, {"roleCode": "designer"}],
    },
    {
        "nickname": "产品-李四",
        "email": "lisi@example.com",
        "mobilePhone": None,
        "avatar": None,
        "gender": None,
        "username": "lisi",
        "isActive": True,
        "roles": [{"roleCode": "user"}, {"roleCode": "product"}],
    },
]

# 菜单数据 (权限表)
INIT_MENUS = [
    {
        "id": 7,
        "title": "导航",
        "name": "Board_77wyja",
        "code": "board",
        "type": 1,
        "path": "/board",
        "icon": "i-mdi-view-dashboard",
        "isLogin": True,
        "sort": 1,
        "children": [
            {
                "id": 8,
                "title": "仪表板",
                "name": "AdminDashboard",
                "code": "admin:dashboard",
                "type": 1,
                "path": "dashboard",
                "componentPath": "views/dashboard/index",
                "icon": "i-mdi-view-dashboard",
                "isLogin": True,
                "sort": 1,
            },
            {
                "id": 9,
                "title": "营销数据",
                "name": "BoardMarketing_wtwmhg",
                "code": "admin:market",
                "type": 1,
                "path": "marketing",
                "componentPath": "views/marketing/index",
                "icon": "i-mdi-shopping ",
                "isLogin": True,
                "sort": 2,
            },
        ],
    },
    {
        "id": 10,
        "title": "功能演示",
        "name": "Showcase_k6vovd",
        "code": "showcase",
        "type": 1,
        "path": "/showcase",
        "icon": "i-mdi-desktop-mac-dashboard",
        "isLogin": True,
        "sort": 2,
        "children": [
            {
                "id": 11,
                "title": "多级导航",
                "name": "ShowcaseIndex",
                "code": "showcase:multilevel",
                "type": 1,
                "path": "#",
                "icon": "i-mdi-sitemap",
                "isLogin": True,
                "sort": 1,
                "children": [
                    {
                        "id": 12,
                        "title": "导航1",
                        "name": "ShowcaseIndexMultiLevelNav",
                        "code": "showcase:multilevel:nav1",
                        "type": 1,
                        "path": "multi-level-nav",
                        "componentPath": "views/tools/showcase/multi-level-nav/index",
                        "icon": "i-mdi-sitemap",
                        "isLogin": True,
                        "sort": 1,
                    },
                    {
                        "id": 13,
                        "title": "导航2",
                        "name": "ShowcaseIndexMultiLevelNav2",
                        "code": "showcase:multilevel:nav2",
                        "type": 1,
                        "path": "#",
                        "icon": "i-mdi-sitemap",
                        "isLogin": True,
                        "sort": 2,
                        "children": [
                            {
                                "id": 14,
                                "title": "导航2-1",
                                "name": "ShowcaseIndexMultiLevelNav21",
                                "code": "showcase:multilevel:nav2:1",
                                "type": 1,
                                "path": "multi-level-nav-2-1",
                                "componentPath": "views/tools/showcase/multi-level-nav/index",
                                "icon": "i-mdi-sitemap",
                                "isLogin": True,
                                "sort": 1,
                            },
                            {
                                "id": 15,
                                "title": "导航2-2",
                                "name": "ShowcaseIndexMultiLevelNav22",
                                "code": "showcase:multilevel:nav2:2",
                                "type": 1,
                                "path": "multi-level-nav-2-2",
                                "componentPath": "views/tools/showcase/multi-level-nav/index",
                                "icon": "i-mdi-sitemap",
                                "isLogin": True,
                                "sort": 2,
                            },
                        ],
                    },
                ],
            },
            {
                "id": 16,
                "title": "标签页",
                "name": "ShowcaseTabs",
                "code": "showcase:tabs",
                "type": 1,
                "path": "tabs",
                "componentPath": "views/tools/showcase/tabs/index",
                "icon": "i-mdi-tab-minus",
                "isLogin": True,
                "sort": 2,
            },
            {
                "id": 17,
                "title": "页面缓存",
                "name": "ShowcasePageCache",
                "code": "showcase:page-cache",
                "type": 1,
                "path": "page-cache",
                "componentPath": "views/tools/showcase/page-cache/index",
                "icon": "i-mdi-tab-plus",
                "isLogin": True,
                "sort": 3,
            },
            {
                "id": 18,
                "title": "局部最大化",
                "name": "ShowcaseMaximize",
                "code": "showcase:maximize",
                "type": 1,
                "path": "maximize",
                "componentPath": "views/tools/showcase/maximize/index",
                "icon": "i-mdi-window-maximize",
                "isLogin": True,
                "sort": 4,
            },
            {
                "id": 19,
                "title": "页面水印",
                "name": "ShowcaseWatermark",
                "code": "showcase:watermark",
                "type": 1,
                "path": "watermark",
                "componentPath": "views/tools/showcase/watermark/index",
                "icon": "i-mdi-watermark",
                "isLogin": True,
                "sort": 5,
            },
            {
                "id": 20,
                "title": "指令复制、防抖、节流",
                "name": "ShowcaseDirectives",
                "code": "showcase:directives",
                "type": 1,
                "path": "directives",
                "componentPath": "views/tools/showcase/directives/index",
                "icon": "i-mdi-script-text",
                "isLogin": True,
                "sort": 6,
            },
            {
                "id": 21,
                "title": "页面刷新",
                "name": "ShowcaseRefresh",
                "code": "showcase:refresh",
                "type": 1,
                "path": "refresh",
                "componentPath": "views/tools/showcase/refresh/index",
                "icon": "i-mdi-refresh",
                "keepAlive": False,
                "isLogin": True,
                "sort": 7,
            },
            {
                "id": 22,
                "title": "国际化",
                "name": "ShowcaseI18nPage",
                "code": "showcase:i18n",
                "type": 1,
                "path": "i18n-page",
                "componentPath": "views/tools/showcase/i18n-page/index",
                "icon": "i-mdi-tab-plus",
                "isLogin": True,
                "sort": 8,
            },
            {
                "id": 23,
                "title": "页面离开提醒",
                "name": "ShowcaseRouteConfirmPage",
                "code": "showcase:route-confirm",
                "type": 1,
                "path": "route-confirm-page",
                "componentPath": "views/tools/showcase/route-confirm-page/index",
                "icon": "i-mdi-exit-to-app",
                "isLogin": True,
                "sort": 9,
            },
            {
                "id": 24,
                "title": "Mock",
                "name": "ShowcaseMockPage",
                "code": "showcase:mock",
                "type": 1,
                "path": "mock-page",
                "componentPath": "views/tools/showcase/mock-page/index",
                "icon": "i-mdi-data-matrix",
                "isLogin": True,
                "sort": 10,
            },
            {
                "id": 25,
                "title": "权限管理体系",
                "name": "ShowcasePermission_fado8p",
                "code": "permission",
                "type": 1,
                "path": "permission",
                "componentPath": "views/tools/showcase/permission/index",
                "icon": "i-mdi-two-factor-authentication",
                "sort": 10,
                "isLogin": True,
            },
        ],
    },
    {
        "id": 26,
        "title": "UI组件",
        "name": "Ui_w70fcu",
        "code": "ui",
        "type": 1,
        "path": "/ui",
        "icon": "i-mdi-widgets",
        "redirect": "message",
        "isLogin": True,
        "sort": 3,
        "children": [
            {
                "id": 27,
                "title": "消息通知 Message",
                "name": "UiMessage",
                "code": "ui:message",
                "type": 1,
                "path": "message",
                "componentPath": "views/tools/showcase/message/index",
                "icon": "i-mdi-message-alert",
                "isLogin": True,
                "sort": 1,
            },
            {
                "id": 28,
                "title": "右键菜单 ContextMenu",
                "name": "UiContextMenu",
                "code": "ui:context-menu",
                "type": 1,
                "path": "context-menu",
                "componentPath": "views/tools/showcase/context-menu/index",
                "icon": "i-mdi-mouse-right-click ",
                "isLogin": True,
                "sort": 2,
            },
            {
                "id": 29,
                "title": "图片预览 Image",
                "name": "UiImagePreviewPage",
                "code": "ui:image-preview",
                "type": 1,
                "path": "image-preview-page",
                "componentPath": "views/tools/showcase/image-preview-page/index",
                "icon": "i-mdi-image-search ",
                "isLogin": True,
                "sort": 3,
            },
            {
                "id": 30,
                "title": "滚动条 Scrollbar",
                "name": "UiScrollbarPage",
                "code": "ui:scrollbar",
                "type": 1,
                "path": "scrollbar-page",
                "componentPath": "views/tools/showcase/scrollbar-page/index",
                "icon": "i-mdi-paper-roll",
                "isLogin": True,
                "sort": 4,
            },
            {
                "id": 31,
                "title": "下拉菜单 Dropdown",
                "name": "UiDropdown",
                "code": "ui:dropdown",
                "type": 1,
                "path": "dropdown",
                "componentPath": "views/tools/showcase/dropdown/index",
                "icon": "i-mdi-form-dropdown",
                "isLogin": True,
                "sort": 5,
            },
            {
                "id": 32,
                "title": "弹出信息 Popover",
                "name": "UiPopoverPage",
                "code": "ui:popover",
                "type": 1,
                "path": "popover",
                "componentPath": "views/tools/showcase/popover-page/index",
                "icon": "i-mdi-forum",
                "isLogin": True,
                "sort": 6,
            },
            {
                "id": 33,
                "title": "间距 Space",
                "name": "UiSpacePage",
                "code": "ui:space",
                "type": 1,
                "path": "space",
                "componentPath": "views/tools/showcase/space-page/index",
                "icon": "i-mdi-forum",
                "isLogin": True,
                "sort": 7,
            },
        ],
    },
    {
        "id": 34,
        "title": "主题",
        "name": "Theme_108dko",
        "code": "theme",
        "type": 1,
        "path": "/theme",
        "icon": "i-mdi-palette-outline",
        "redirect": "show",
        "isLogin": True,
        "sort": 4,
        "children": [
            {
                "id": 35,
                "title": "主题展示",
                "name": "ThemeShow",
                "code": "theme:show",
                "type": 1,
                "path": "show",
                "componentPath": "views/tools/theme/show/index",
                "icon": "i-mdi-palette",
                "isLogin": True,
                "sort": 1,
            },
            {
                "id": 36,
                "title": "主题数据",
                "name": "ThemeDatas",
                "code": "theme:datas",
                "type": 1,
                "path": "datas",
                "componentPath": "views/tools/theme/datas/index",
                "icon": "i-mdi-invert-colors",
                "isLogin": True,
                "sort": 2,
            },
            {
                "id": 37,
                "title": "主题编辑器",
                "name": "ThemeNaiveuiEditor",
                "code": "theme:editor",
                "type": 1,
                "path": "naiveui-editor",
                "componentPath": "views/tools/theme/naiveui-editor/index",
                "icon": "i-mdi-tag-edit",
                "isLogin": True,
                "sort": 3,
            },
        ],
    },
    {
        "id": 38,
        "title": "图片库",
        "name": "ImageManagement_feygps",
        "code": "image:management",
        "type": 1,
        "path": "/image-management",
        "icon": "i-mdi-image-multiple",
        "isLogin": True,
        "sort": 5,
        "children": [
            {
                "id": 39,
                "title": "图片库",
                "name": "ImageManagementIndex",
                "code": "image:list",
                "type": 1,
                "componentPath": "views/image-management/index",
                "icon": "i-mdi-image-multiple",
                "hideInMenu": True,
                "isLogin": True,
                "sort": 1,
            }
        ],
    },
    {
        "id": 40,
        "title": "异常页面",
        "name": "Exception_eozq3s",
        "code": "exception",
        "type": 1,
        "path": "/exception",
        "icon": "i-mdi-alert-circle",
        "redirect": "403",
        "isLogin": True,
        "sort": 6,
        "children": [
            {
                "id": 41,
                "title": "403",
                "name": "Exception403",
                "code": "exception:403",
                "type": 1,
                "path": "403",
                "componentPath": "views/exception/index",
                "icon": "i-mdi-alert-circle-outline",
                "isLogin": True,
                "sort": 1,
            },
            {
                "id": 42,
                "title": "404",
                "name": "Exception404",
                "code": "exception:404",
                "type": 1,
                "path": "404",
                "componentPath": "views/exception/index",
                "icon": "i-mdi-lock-outline",
                "isLogin": True,
                "sort": 2,
            },
            {
                "id": 43,
                "title": "500",
                "name": "Exception500",
                "code": "exception:500",
                "type": 1,
                "path": "500",
                "componentPath": "views/exception/index",
                "icon": "i-mdi-bug-outline",
                "isLogin": True,
                "sort": 3,
            },
        ],
    },
    {
        "id": 44,
        "title": "友情链接",
        "name": "Blogroll_mf0sx0",
        "code": "blogroll",
        "type": 1,
        "path": "/blogroll",
        "icon": "i-mdi-link-variant",
        "isLogin": True,
        "sort": 7,
        "children": [
            {
                "id": 45,
                "title": "github",
                "name": "BlogrollGithub",
                "code": "blogroll:github",
                "type": 1,
                "path": "shadcn-ui",
                "icon": "i-mdi-link-variant ",
                "link": "https://github.com/fffmoon/banana-flow-admin",
                "isLogin": True,
                "sort": 1,
            },
            {
                "id": 46,
                "title": "reka-ui",
                "name": "BlogrollRekaUi",
                "code": "blogroll:rekaui",
                "type": 1,
                "path": "shadcn-ui",
                "icon": "i-mdi-link-variant ",
                "link": "https://reka-ui.com",
                "isLogin": True,
                "sort": 2,
            },
            {
                "id": 47,
                "title": "shadcn-ui",
                "name": "BlogrollShadcnUi",
                "code": "blogroll:shadcnui",
                "type": 1,
                "path": "shadcn-ui",
                "icon": "i-mdi-link-variant ",
                "link": "https://ui.shadcn.com",
                "isLogin": True,
                "sort": 3,
            },
        ],
    },
    {
        "id": 48,
        "title": "系统管理",
        "name": "System_klc5mo",
        "code": "system",
        "type": 1,
        "path": "/system",
        "icon": "i-mdi-cog",
        "isLogin": True,
        "sort": 8,
        "children": [
            {
                "id": 49,
                "title": "菜单管理",
                "name": "SystemMenu_xspi58",
                "code": "system:menu",
                "type": 1,
                "path": "menu",
                "componentPath": "views/system/menu/index",
                "icon": "i-mdi-format-list-bulleted",
                "isLogin": True,
                "sort": 1,
                "children": [
                    {
                        "id": 50,
                        "title": "新增权限",
                        "name": "",
                        "code": "system:menu:create",
                        "type": 2,
                        "sort": 1,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 51,
                        "title": "编辑权限",
                        "name": "",
                        "code": "system:menu:update",
                        "type": 2,
                        "sort": 2,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 52,
                        "title": "删除权限",
                        "name": "",
                        "code": "system:menu:delete",
                        "type": 2,
                        "sort": 3,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 53,
                        "title": "获取权限列表",
                        "name": "",
                        "code": "system:menu:list",
                        "type": 2,
                        "sort": 4,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                ],
            },
            {
                "id": 54,
                "title": "角色管理",
                "name": "SystemRoles",
                "code": "system:role",
                "type": 1,
                "path": "roles",
                "componentPath": "views/system/role/index",
                "icon": "i-mdi-shield-account",
                "isLogin": True,
                "auths": [],
                "auth": [],
                "sort": 2,
                "children": [
                    {
                        "id": 55,
                        "title": "新增角色",
                        "name": "",
                        "code": "system:roles:create",
                        "type": 2,
                        "sort": 1,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 56,
                        "title": "编辑角色",
                        "name": "",
                        "code": "system:roles:update",
                        "type": 2,
                        "sort": 2,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 57,
                        "title": "删除角色",
                        "name": "",
                        "code": "system:roles:delete",
                        "type": 2,
                        "sort": 3,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 58,
                        "title": "分配菜单权限",
                        "name": "",
                        "code": "system:roles:assign_menus",
                        "type": 2,
                        "sort": 4,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 59,
                        "title": "获取角色列表",
                        "name": "",
                        "code": "system:roles:list",
                        "type": 2,
                        "sort": 5,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                ],
            },
            {
                "id": 60,
                "title": "用户管理",
                "name": "SystemUser",
                "code": "system:user",
                "type": 1,
                "path": "user",
                "componentPath": "views/system/user/index",
                "icon": "i-mdi-account",
                "isLogin": True,
                "auths": [],
                "auth": [],
                "sort": 3,
                "children": [
                    {
                        "id": 61,
                        "title": "新增用户",
                        "name": "",
                        "code": "system:users:create",
                        "type": 2,
                        "sort": 1,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 62,
                        "title": "编辑用户",
                        "name": "",
                        "code": "system:users:update",
                        "type": 2,
                        "sort": 2,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 63,
                        "title": "删除用户",
                        "name": "",
                        "code": "system:users:delete",
                        "type": 2,
                        "sort": 3,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                    {
                        "id": 64,
                        "title": "获取用户列表",
                        "name": "",
                        "code": "system:users:list",
                        "type": 2,
                        "sort": 4,
                        "isLogin": True,
                        "auths": [],
                        "auth": [],
                        "query": {},
                    },
                ],
            },
            {
                "id": 65,
                "title": "操作日志",
                "name": "SystemOperationLog_t4srva",
                "code": "system:operation-log",
                "type": 1,
                "path": "operation-log",
                "componentPath": "views/system/operation-log/index",
                "icon": "i-mdi-file-document-outline",
                "isLogin": True,
                "auths": [],
                "auth": [],
                "sort": 4,
            },
        ],
    },
]
